# Generated by Django 5.0.6 on 2024-05-13 04:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=60, verbose_name='Тема'), size=10)),
                ('solution_count', models.CharField(max_length=60, verbose_name='Количество решений')),
                ('name_with_index', models.CharField(max_length=60, verbose_name='Название и номер')),
                ('difficulty', models.IntegerField(verbose_name='Сложность')),
            ],
        ),
    ]
