# Generated by Django 5.0.6 on 2024-05-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='solution_count',
            field=models.IntegerField(verbose_name='Количество решений'),
        ),
    ]
