# Generated by Django 5.0.6 on 2024-05-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_name_with_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
