# Generated by Django 5.0.6 on 2024-05-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_from', models.IntegerField(verbose_name='Нижняя граница сложности')),
                ('difficulty_to', models.IntegerField(verbose_name='Верхняя граница сложности')),
                ('subject', models.CharField(max_length=100, verbose_name='Тема')),
                ('tasks', models.ManyToManyField(to='tasks.task')),
            ],
        ),
    ]
